### ISSUE TITLE
moreStyleSheets needs better name

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/construct-stylesheets#3]

**Comment by calebdwilliams** [comment]
Yeah, `moreStyleSheets` feels sloppy and not really indicative to a developer what's actually happening under the hood. I like the idea of `constructedStyleSheets`, `customStyleSheets` (or somehow otherwise designating that it is equivalent to a user agent stylesheet) or `elementStyleSheets` as it gets to what the actual distinction between the lists are.

**Comment by TakayoshiKochi** [comment]
This discussion should depend on how the constructed stylesheet would be used, and how it behaves against other existing stylesheets.

At this point, custom element default style seems the first customer of the constructed stylesheet, and it doesn't depend on how this name is defined.

**Comment by TakayoshiKochi** [comment]
As of now https://github.com/w3c/webcomponents/issues/468 is the primary use case of constructed stylesheet, and `.moreStyleSheets` is not necessary for now.

Once its use case is invented by someone, let's revisit and bikeshed for the name.

**Comment by calebdwilliams** [comment]
This should be reopened per [this pull request comment](https://github.com/WICG/construct-stylesheets/pull/33#issuecomment-416616478). There I suggested `adoptedStyleSheets` if this is to be a property of a document/document fragment/element that will essentially adopt an outside style sheet. This also accounts for potential [CSS/JS imports ](https://github.com/w3c/webcomponents/issues/759) and that use case.

**Comment by rakina** [comment]
We decided on `adoptedStyleSheets`. Thanks @calebdwilliams!
