### ISSUE TITLE
`[Constructor]` can't be used on partial interfaces

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#73]
`[Constructor]` is defined in Web IDL to only be allowed on interfaces, not partial interfaces.  It looks like at least some browsers' IDL parsers don't enforce this, unfortunately, and make up some sort of semantics for what it means on a partial interface.

Either the `[Constructor]` needs to be moved into CSSOM or Web IDL needs to be changed to allow `[Constructor]` on partial interfaces and specify how it works.

**Comment by domenic** [comment]
This is one of the big reasons we're hoping to move to CSSOM. Unfortunately it looks like due to CSSWG policies that would involve a lot of adminstrative effort (duplicate specifications): https://github.com/w3c/csswg-drafts/issues/3433

In the meantime, do you think there's any way to make the intent clearer here?

**Comment by bzbarsky** [comment]
I think just adding an informative note that this is a known issue, that the intent is for the `[Constructor]` to be on the main interface definition, and pointing to the merging discussion is fine.  I agree that merging into CSSOM is the right thing here; I'm sorry it's such a pain.  :(
