### ISSUE TITLE
Debug Adoptet StyleSheets

### ISSUE THREAD

**Issue by jogibear9988** [WICG/construct-stylesheets#99]
How can I debug those styles? As I don't see them in the chrome inspector

**Comment by rakina** [comment]
Hi, sorry for the late reply, somehow this slipped through. This issue is currently being fixed in Chrome DevTools, here's the tracking bug: https://bugs.chromium.org/p/chromium/issues/detail?id=946975.
I'll close this issue here as this repo is more for the spec side of things. For Chrome/Blink-specific bugs, please file them through crbug.com.
